package org.wfanet.panelmatch.common

import java.security.cert.X509Certificate

/**
 * Interface to grab and validate certificates. Provides validated X509 certificates for an exchange
 * to use to validate .
 */
interface CertificateManager {

  /** Grabs certificates generated by the executing party. */
  suspend fun getOwnedExchangeCertificate(exchangeKeyName: String): X509Certificate

  /** Grabs certificates generated by the other party in the exchange. */
  suspend fun getPartnerExchangeCertificate(
    exchangeKeyName: String,
    partnerName: String,
  ): X509Certificate

  /**
   * Grabs a root certificate for one member of a recurring exchange that the caller is a part of.
   */
  suspend fun getPartnerExchangeRootCertificate(
    exchangeKeyName: String,
    partnerName: String,
  ): X509Certificate
}
